name: Python CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('app_python/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app_python/requirements.txt

      - name: Lint code
        run: |
          pip install flake8
          flake8 app_python

      - name: Run tests
        run: |
          pip install pytest
          pytest app_python/test_main.py

  security:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.10@master
        with:
          args: --skip-unresolved app_python/
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker:
    runs-on: ubuntu-latest

    needs:
      - build
      - security
    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build  Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app_python:latest ./app_python

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/app_python:latest